cmake_minimum_required(VERSION 3.0.2)
project(car_control_ros)
find_package(catkin REQUIRED COMPONENTS rospy std_msgs std_srvs geometry_msgs sensor_msgs nav_msgs visualization_msgs message_generation)
catkin_python_setup()
add_message_files(FILES Cone.msg ConeArray.msg Drive.msg)
generate_messages(DEPENDENCIES std_msgs geometry_msgs)
catkin_package(CATKIN_DEPENDS message_runtime rospy std_msgs std_srvs geometry_msgs sensor_msgs nav_msgs visualization_msgs)
catkin_install_python(PROGRAMS scripts/controller_node.py scripts/simulator_node.py scripts/fsds_node.py scripts/vision_node.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY launch config DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
get_filename_component(PACKAGE_SOURCE "${CMAKE_CURRENT_SOURCE_DIR}" REALPATH)
install(DIRECTORY "${PACKAGE_SOURCE}/../../Jetson Xavier/Code" DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/legacy FILES_MATCHING PATTERN "*.py")
install(FILES "${PACKAGE_SOURCE}/../../Jetson Xavier/config.jsonc" DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/legacy)
if(CATKIN_ENABLE_TESTING)
  find_package(rostest REQUIRED)
  catkin_install_python(PROGRAMS test/ros_smoke.py test/ros_watchdog.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
  add_rostest(test/smoke.test)
  add_rostest(test/watchdog.test)
endif()
